#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
WORKING_DIR=../$SCRIPT_DIR
BAZEL=bazel

function switch_to_working_dir() {
  cd $WORKING_DIR
}

function build_protos() {
  switch_to_working_dir
  ${BAZEL} build //pulp_fiction_ios_app:build_swift_protos --apple_platform_type=ios
}

function build_source() {
  switch_to_working_dir
  ${BAZEL} build //pulp_fiction_ios_app:build_source --apple_platform_type=ios
}

function format() {
  switch_to_working_dir
  ${BAZEL} build //pulp_fiction_ios_app:format && ${BAZEL} run //pulp_fiction_ios_app:format_update
}