version: 2.1

parameters:
  should_build_java_ci_image:
    type: boolean
    default: false

jobs:
  build_java_ci_image:
    working_directory: /app
    docker:
      - image: kernald/bazel:5.1.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build CI Image
          command: |
            bazel build \
            --action_env=DOCKER_CERT_PATH=${DOCKER_CERT_PATH} \
            --action_env=DOCKER_HOST=${DOCKER_HOST} \
            --action_env=DOCKER_MACHINE_NAME=${DOCKER_MACHINE_NAME} \
            --action_env=DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY} \
            --action_env=NO_PROXY=${NO_PROXY} \
            //docker_images/java_ci_image:build_image

workflows:
  build_java_ci_image:
    when: << pipeline.parameters.should_build_java_ci_image >>
    jobs:
      - build_java_ci_image
