load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "pulp_fiction_proto",
    srcs = ["pulp_fiction.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
    ],
)
