//
//  ProtoAliases.swift
//  _idx_PictureSaverSource_6C36F415_ios_min15.0
//
//  Created by Matthew Dornfeld on 5/22/22.
//

import Foundation
import protos_pulp_fiction_grpc_stubs_swift
import protos_pulp_fiction_grpc_swift
import protos_pulp_fiction_proto
import SwiftProtobuf

public typealias CreateLoginSessionRequest = PulpFiction_Protos_CreateLoginSessionRequest
public typealias CreateLoginSessionResponse = PulpFiction_Protos_CreateLoginSessionResponse
public typealias CreatePostRequest = PulpFiction_Protos_CreatePostRequest
public typealias CreatePostResponse = PulpFiction_Protos_CreatePostResponse
public typealias CreateUserRequest = PulpFiction_Protos_CreateUserRequest
public typealias CreateUserResponse = PulpFiction_Protos_CreateUserResponse
public typealias GetFeedRequest = PulpFiction_Protos_GetFeedRequest
public typealias GetFeedResponse = PulpFiction_Protos_GetFeedResponse
public typealias ImagePost = PulpFiction_Protos_Post.ImagePost
public typealias Post = PulpFiction_Protos_Post
public typealias PulpFictionClientProtocol = PulpFiction_Protos_PulpFictionClientProtocol
public typealias PulpFictionServiceClient = PulpFiction_Protos_PulpFictionClient
public typealias PulpFictionTestClient = PulpFiction_Protos_PulpFictionTestClient
public typealias SensitiveUserMetadataProto = PulpFiction_Protos_User.SensitiveUserMetadata
public typealias UpdateLoginSessionRequest = PulpFiction_Protos_UpdateLoginSessionRequest
public typealias UpdateLoginSessionResponse = PulpFiction_Protos_UpdateLoginSessionResponse
public typealias UpdatePostRequest = PulpFiction_Protos_UpdatePostRequest
public typealias UpdatePostResponse = PulpFiction_Protos_UpdatePostResponse
public typealias UpdateUserRequest = PulpFiction_Protos_UpdateUserRequest
public typealias UpdateUserResponse = PulpFiction_Protos_UpdateUserResponse
public typealias UserMetadataProto = PulpFiction_Protos_User.UserMetadata

public typealias UserFollowingStatus = UpdateUserRequest.UpdateUserFollowingStatus.UserFollowingStatus
public typealias ContactVerificationProto = UpdateUserRequest.UpdateSensitiveUserMetadata.VerifyContactInformation.ContactVerification
